### ISSUE TITLE
Bib2gls

### ISSUE THREAD

**Issue by Martin-2019** [wtsnjp/llmk#13]
Dear Maintainer!

How to use bib2gls with the llmk program, with options, just like for the arara program (sequence), eg.:

% arara: lualatex: { shell: yes, synctex: yes }
% arara: bib2gls: { group: on , recordcount: on , breakspace: on }
% arara: lualatex: { shell: yes, synctex: yes }
% arara: bib2gls: { group: on , recordcount: on , breakspace: on }
% arara: lualatex: { shell: yes, synctex: yes }
% arara: biber
% arara: lualatex: { shell: yes, synctex: yes }
% arara: lualatex: { shell: yes, synctex: yes }

Is this possible? If so, it might be worth adding to the manual - as an example.

Regards

M.

**Comment by wtsnjp** [comment]
You can configure several general features, including that command-line options (`opts`) to treat any kind of program in the `programs` table. Please see Section 3.4 of the reference manual.

I'm not familiar with bib2gls. Is there anything special point for the invocation of bib2gls? Maybe you need to run the `latex` program as its `postprocess`?

```toml
[programs.bib2gls]
command = "bib2gls"
target = "%B.aux"  # is this correct?
opts = ["<any option you want>"]
postprocess = "latex"
```

If there are standard (or recommended) options for general users, then I can add the setting to the default `programs` table and indeed write it down in the manual as we as the other programs.
