### ISSUE TITLE
`biber` not executed with `biblatex`

### ISSUE THREAD

**Issue by LWisteria** [wtsnjp/llmk#20]
When using `llmk` with following `llmk.toml`, `biber` is never executed.

```toml
source = "main.tex"
output_directory = "build"

[programs.bibtex]
command = "biber"
opts = ["--input_directory=%o", "--output_directory=%o"]
```

Adding `target = "%B.bcf"` on `[programs.bibtex]` fixes this problem.

Is this your intended behavior? It seems like a common use case (using biblatex/biber with an output_directory) that perhaps should work by default without requiring manual target configuration.

Thanks
